# Generated by Django 5.1.4 on 2025-02-01 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0004_post_tagg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tagg',
            new_name='tags',
        ),
    ]
